// Enunciado
// El programa genera un número secreto entre 1 y 100. El usuario tiene máximo 7 intentos para
// adivinarlo. Después de cada intento, el programa dice si el número secreto es mayor o menor.
// El juego termina cuando el usuario adivina o se le acaban los intentos. Si adivina, mostrar en
// cuántos intentos lo logró. Si pierde, mostrar cuál era el número.
// Para generar el número usa: Math.floor(Math.random() * 100) + 1.