// Una empresa necesita calcular el salario semanal de N obreros. Leer N y luego las horas
// trabajadas de cada obrero.
// Si el obrero trabaja 40 horas o menos, se le paga $12.000 por hora. Si trabaja más de 40, se le
// pagan $12.000 por cada una de las primeras 40 horas y $15.000 por cada hora extra. Mostrar
// el salario de cada obrero y el total de la nómina.
let N=0
let Horas=0
parseInt(prompt('ingrese la cantidad de obreros $'{N}))
for (i=1 ;1=N; i++){
const obrero=parseInt(prompt('Ingrese el obrero $'{i}))
if (obrero)

}